baseURL = 'https://blog.edward-li.com/'
languageCode = 'en-us'
title = "Edward Li's Blog"
copyright = "Edward Li"
theme = 'hydra-devel'

[[menu.main]]
name = "Blogs"
url = "/"
weight = 1

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3

[[menu.main]]
name = "Home"
url = "https://edward-li.com/"
weight = 4

[params]
colortheme = "white"
logo = "static/images/logo.png"
description = """I'm Edward Li, a Computer Science and Physics student at the [University of British Columbia](https://www.ubc.ca)! 
Currently, I live in San Francisco building software agents at [Codegen](https://codegen.com/).

I also play CTFs with [MapleBacon](https://maplebacon.org) and [MMM](https://x.com/mmm_ctf_team),
build rockets with [UBC Rocket](https://ubcrocket.com),
organize logistics for [nwPlus](https://nwplus.io),
and foster communities at [Atelier](https://www.instagram.com/atelier.ubc/)/[Socratica](https://www.socratica.info).

This blog serves as a collection of my thoughts, projects, and experiences over the years. Feel free to explore!"""
mainSectionTitle = "Blog Posts"
mainSections = []
displayCategories = []
showAllPostsArchive = true
showAllPostsOnHomePage = true
enableBlogCategoryHeaders = true
themeFooter = true

[[module.mounts]]
source = 'static'
target = 'static/static'